// codegen.rs
use crate::ast::{BinaryOp, Literal, Type, UnaryOp};
use crate::mir::*;
use crate::intrinsic::{IntrinsicFn, get_intrinsic};
use std::collections::HashMap;

#[derive(Clone)]
struct CodegenContext {
    locals: HashMap<usize, String>,
    enum_variants: HashMap<String, Vec<String>>,
    enum_variant_has_payload: HashMap<String, Vec<bool>>,
}

impl CodegenContext {
    fn get_variants(&self, enum_name: &str) -> Option<&Vec<String>> {
        self.enum_variants.get(enum_name)
    }
}

pub struct Codegen;

impl Codegen {
    // ===== 主入口 =====
    pub fn generate_from_mir(program: &MirProgram) -> String {
        let mut code = String::new();
        code.push_str("// Generated by Xiyi Compiler (MIR backend)\n\n");
        code.push_str("// ---- Privacy labels (compile-time only) ----\n");
        code.push_str("pub trait PrivacyLevel {}\n");
        code.push_str("pub struct Public;\n");
        code.push_str("pub struct Private;\n");
        code.push_str("pub struct Dp<const EPS_NUM: i128, const EPS_DEN: u128>;\n");
        code.push_str("impl PrivacyLevel for Public {}\n");
        code.push_str("impl PrivacyLevel for Private {}\n");
        code.push_str("impl<const N: i128, const D: u128> PrivacyLevel for Dp<N, D> {}\n");
        code.push_str("pub struct PrivacyTensor<T, L: PrivacyLevel>(pub T, pub std::marker::PhantomData<L>);\n\n");

        // 结构体
        for s in &program.structs {
            code.push_str(&Self::gen_struct(s));
        }

        // 枚举
        for e in &program.enums {
            code.push_str(&Self::gen_enum(e));
        }

        let enum_variants: HashMap<String, Vec<String>> = program.enums
            .iter()
        .map(|e| {
            let variants: Vec<String> = e.variants.iter().map(|(name, _)| name.clone()).collect();
            (e.name.clone(), variants)
        })
        .collect();

        let enum_variant_has_payload: HashMap<String, Vec<bool>> = program.enums
            .iter()
            .map(|e| {
                let has: Vec<bool> = e.variants.iter().map(|(_, ty)| ty.is_some()).collect();
                (e.name.clone(), has)
            })
            .collect();

        // 函数
        for f in &program.fns {
            code.push_str(&Self::gen_function(f, &enum_variants, &enum_variant_has_payload));
        }

        // 如果没有 main，自动生成一个占位
        if !program.fns.iter().any(|f| f.name == "main") {
            code.push_str("fn main() {\n    println!(\"Hello from Xiyi!\");\n}\n");
        }

        code
    }

    // ===== 生成结构体 =====
    fn gen_struct(s: &MirStruct) -> String {
        let generic = if s.generic_params.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = s.generic_params.iter().map(|p| p.name.clone()).collect();
            format!("<{}>", params.join(", "))
        };
        let mut code = format!("#[derive(Debug, Clone, PartialEq)]\nstruct {}{} {{\n", s.name, generic);
        for (name, ty) in &s.fields {
            code.push_str(&format!("    pub {}: {},\n", name, Self::type_to_rust(ty)));
        }
        code.push_str("}\n\n");
        code
    }

    // ===== 生成枚举 =====
    fn gen_enum(e: &MirEnum) -> String {
        let generic = if e.generic_params.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = e.generic_params.iter().map(|p| p.name.clone()).collect();
            format!("<{}>", params.join(", "))
        };
        let mut code = format!("#[derive(Debug, Clone, PartialEq)]\nenum {}{} {{\n", e.name, generic);
        for (name, ty) in &e.variants {
            if let Some(ty) = ty {
                code.push_str(&format!("    {}({}),\n", name, Self::type_to_rust(ty)));
            } else {
                code.push_str(&format!("    {},\n", name));
            }
        }
        code.push_str("}\n\n");
        code
    }

    // ===== 生成函数 =====
    fn gen_function(
        f: &MirFn,
        enum_variants: &HashMap<String, Vec<String>>,
        enum_variant_has_payload: &HashMap<String, Vec<bool>>,
    ) -> String {
        let generic = if f.generic_params.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = f.generic_params.iter().map(|p| p.name.clone()).collect();
            format!("<{}>", params.join(", "))
        };

        let params_str: Vec<String> = f.params.iter()
            .map(|(name, ty)| format!("{}: {}", name, Self::type_to_rust(ty)))
            .collect();

        let ret_str = if let Some(ty) = &f.return_type {
            format!(" -> {}", Self::type_to_rust(ty))
        } else {
            String::new()
        };

        let mut code = format!(
            "#[allow(unused_mut, unused_variables, unreachable_code, dead_code)]\nfn {}{}({}){} {{\n",
            f.name, generic, params_str.join(", "), ret_str
        );

        // ---- 构建 local_map ----
        // 关键修复（最严重的一处——原来的写法会让几乎每个函数生成出来
        // 的 Rust 代码都编译不过）：
        //
        // `f.body.locals` 是按 base id 登记的，一个 id 只登记一次；但
        // mir_builder.rs 里 `let`/赋值语句的 dest 几乎全是
        // `MirPlace::Ssa(SsaLocal{base_id, version})`——同一个 base_id
        // 只要被重新赋值过，就会有多个不同的 version（比如循环里
        // `x = x + 1` 反复执行，对应 x_v1、x_v2、x_v3……）。原来
        // `place_to_string` 给 `MirPlace::Ssa` 生成的名字是
        // `format!("__ssa_{}_{}", ssa.base_id, ssa.version)`——带 version
        // 号；而这里的声明循环只按 `local.id`（也就是 base_id）声明了
        // 一个变量（用 `local.name` 或者 `__tmp_{id}` 命名，根本不带
        // version）。这两套命名完全对不上：`__ssa_5_1`、`__ssa_5_2` 这些
        // 名字从来没有被 `let` 声明过，直接用会是"cannot find value
        // `__ssa_5_1` in this scope"——只要一个函数体里出现过 SSA 版本号
        // 大于 0（也就是几乎所有非平凡函数），生成的代码就通不过编译。
        //
        // 正确的做法是把同一个 base_id 的所有 SSA 版本"折叠"回同一个
        // Rust 变量——这本来就是从 SSA 形式降到普通命令式代码的标准
        // 做法（数据流只要求"每次读到的是离它最近的那次写"，并不需要
        // 真的保留版本号这层区分；只要写读的先后顺序保持不变，折叠成
        // 同一个变量不会改变语义）。这样 `MirPlace::Ssa` 就能直接复用
        // 已经在下面按 base_id 建好的 `ctx.locals`，不需要另起一套
        // 单独的按版本号声明的机制。
        let mut local_map: HashMap<usize, String> = HashMap::new();
        for local in &f.body.locals {
            let name = local.name.clone().unwrap_or_else(|| format!("__tmp_{}", local.id));
            local_map.insert(local.id, name.clone());

            if local.is_param {
                continue;
            }

            // 关键修复：这里原来是 `if local.mutable { "mut " } else { "" }`
            // ——`mutable` 反映的是"源语言里是不是用 var 声明的"，这跟
            // "生成出来的这个 Rust 变量要不要 mut"是两件不同的事。
            // 问题出在 loop+match 分发这套结构本身：一个 while/for 循环
            // 展开成 MIR 之后，循环体对应的是某几个块，靠 Goto 回边跳回
            // 循环条件块——这些块在生成的 Rust 里是 `loop { match
            // __block { ... } }` 里的某几个 match 分支，只要 __block
            // 的值会绕回来，这几个分支在一次函数调用里就可能被执行
            // 多次。哪怕源代码里这个变量是不可变的 `let`（每次循环迭代
            // 里只写一次，`mutable=false`），折叠到同一个 Rust 变量后，
            // 对应的赋值语句在 Rust 源码里是同一行代码、位于循环内部，
            // Rust 的可变性检查是按"这段代码在源码结构上会不会被多次
            // 执行"来判断的，不关心"语义上其实每次都是新的一份值"——
            // 循环体内对一个 non-mut 变量赋值，就算只有一份"逻辑上的"
            // 值，Rust 也会因为它在循环体内被拒绝编译（"cannot assign
            // twice to immutable variable"）。稳妥的办法是干脆统一都用
            // `mut`——多标一个不需要的 `mut` 只会触发一条 warning（函数
            // 顶上已经有 `#[allow(unused_mut, ...)]` 把这条 warning 也
            // 消掉了），永远不会导致编译错误；反过来漏标 `mut` 则会在
            // "折叠后的变量恰好落在循环体内"这种情况下直接编译不过。
            code.push_str(&format!("    let mut {}: {};\n", name, Self::type_to_rust(&local.ty)));
        }

        let ctx = CodegenContext {
            locals: local_map,
            enum_variants: enum_variants.clone(),
            enum_variant_has_payload: enum_variant_has_payload.clone(),
        };

        // ---- 生成函数体 ----
        code.push_str(&Self::gen_function_body(&f.body, &ctx));

        code.push_str("}\n\n");
        code
    }

    // ===== 函数体：把基本块图落回安全 Rust =====
    fn gen_function_body(body: &MirBody, ctx: &CodegenContext) -> String {
        let mut code = String::new();

        // 关键修复：原来这里就是单纯按 f.body.blocks 的数组顺序把每个
        // 块的语句首尾拼接起来，Goto/If 全都只落一行注释（"// goto
        // block N"），注释在生成出来的 Rust 里什么都不做。只要函数体里
        // 出现一次分支或者循环（loop 展开出的回边 Goto），生成代码就从
        // "看起来能编译"退化成"编译能过、执行结果却是错的"——比如
        // `while cond { body }` 会被拉直成"不管 cond 是什么，先原样执行
        // 一遍 body，然后接着往下走"：不会重复、也不会在 cond 为假时
        // 跳过。这不是某个 corner case，是"只要有 if/while/for/loop 就
        // 会错"，覆盖了几乎所有非平凡函数。
        //
        // Rust 没有 goto，修法是编译到无 goto 目标语言时的标准手法：
        // "loop + 块号 match 分发"——引入一个 usize 变量记录"下一个要
        // 执行的块"，每个 MirBlock 变成 match 的一个分支，Goto/If 从
        // "写一行不做事的注释"变成"把块号变量设成目标块、continue 回到
        // loop 顶部重新 match"。这套手法对任意控制流图（包括循环的回边）
        // 都是正确的，代价只是多一层 loop 和一个 usize 变量，不需要真的
        // 去做"识别这段 CFG 长得像不像 if/while/for"这种结构化恢复。
        //
        // 只有一个块的函数（没有分支、没有循环）是这套机制里唯一的
        // 特例：既然只有一个块，Goto/If 就不可能有第二个块可跳，直接把
        // 语句和终止器拍平进函数体，生成的代码更接近手写、可读性更好；
        // 如果这种"单块函数"的终止器居然是 Goto/If，那是上游 CFG 构造
        // 出了 bug（该开新块的地方没开），交给 gen_terminator_single 里
        // 的 unreachable!() 在生成代码里直接炸出来，而不是在这里悄悄
        // 按"反正只有一块"的假设吞掉。
        if body.blocks.len() <= 1 {
            if let Some(block) = body.blocks.first() {
                for stmt in &block.stmts {
                    code.push_str(&Self::gen_stmt(stmt, ctx));
                }
                code.push_str(&Self::gen_terminator_single(&block.terminator, ctx));
            }
            return code;
        }

        // 关键修复（严重：优化跑完之后基本必炸）：这里原来用的是
        // `block.id`（块自己存的那个字段）当 match 分支的标号。但
        // control.rs/simplify.rs 里所有的死块消除、块合并、空块折叠
        // 那些优化过程（remove_dead_blocks、collapse_empty_blocks、
        // merge_blocks……），在把幸存的块搬进新的 `Vec<MirBlock>` 时，
        // 靠的都是"新 Vec 里的下标位置"这个身份——Goto/If/Switch 的跳转
        // 目标全部被重写成新的下标，但没有任何一处会同步去改块自己那个
        // `.id` 字段（这些函数只是 `.clone()` 整个块搬过去，`.id`
        // 还是优化前的旧值）。也就是说优化跑完之后，`block.id` 和这个
        // 块在 `body.blocks` 里的实际下标基本必然对不上——这里如果继续
        // 拿 `block.id` 当 match 标号，而跳转目标（`__block = N;`）用的
        // 是下标，两边根本不是同一套编号：match 永远走不到期望的那个
        // 分支，落到 `_ => unreachable!("invalid block id")` 直接
        // panic。只要函数经过了任何一趟这些优化（几乎所有函数都会），
        // 生成出来的代码运行时就会炸。
        //
        // 改成用 `.enumerate()` 拿到的下标当标号，这跟整条优化流水线
        // 里"跳转目标全部是下标"的约定保持一致，`.id` 这个字段对
        // codegen 来说不再需要读。
        code.push_str("    let mut __block: usize = 0;\n");
        code.push_str("    loop {\n");
        code.push_str("    match __block {\n");
        for (idx, block) in body.blocks.iter().enumerate() {
            code.push_str(&format!("        {} => {{\n", idx));
            for stmt in &block.stmts {
                code.push_str(&format!("    {}", Self::gen_stmt(stmt, ctx)));
            }
            code.push_str(&Self::gen_terminator_dispatch(&block.terminator, ctx));
            code.push_str("        }\n");
        }
        code.push_str("        _ => unreachable!(\"invalid block id\"),\n");
        code.push_str("    }\n");
        code.push_str("    }\n");
        code
    }

    // ===== 生成语句 =====
    fn gen_stmt(stmt: &MirStmt, ctx: &CodegenContext) -> String {
        match stmt {
            // 关键新增：Phi 节点需要在这里单独拦一道，不能走下面通用的
            // `dest = rvalue_to_string(value);` 路径。
            //
            // mir_builder.rs 现在会真的生成 MirRvalue::Phi 了（以前只是
            // 占位、从没真正用过），但这套 codegen 用的是"把同一个
            // base_id 的所有 SSA 版本折叠成同一个 Rust 变量"的策略（见
            // place_to_string 里 MirPlace::Ssa 那支的说明）。这个策略
            // 恰好让 Phi 变得没必要生成任何代码：观察 mir_builder.rs
            // 现在生成 Phi 的方式——不管是 If 的 then/else 分支，还是
            // Match 每个 arm 分支，各自往里写的那个"分支结果"用的都是
            // `self.new_version(dest_base)`，也就是说 Phi 自己的 dest
            // 和它 values 列表里的每一路操作数，全部共享同一个
            // base_id。既然折叠策略已经把这一整个 base_id 家族映射到
            // 了同一个 Rust 变量，那么执行到 Phi 语句这里的时候，随便
            // 是从哪个分支走过来的，这个变量早就已经被那个分支自己的
            // 赋值语句写成正确的值了——Phi 要做的"合并"这件事，已经
            // 被"折叠成同一个变量"这个动作提前完成了，不需要再生成
            // 任何代码。
            //
            // 这里没有偷懒地无条件假设这一点成立，而是先检查一遍：
            // 如果哪一路操作数引用的不是跟 dest 同一个 base_id 的
            // SsaLocal（说明以后 mir_builder.rs 生成 Phi 的方式变了，
            // 不再满足这条"共享 base_id"的前提——那种情况需要一次真正
            // 的"在每个来源块末尾插入一条赋值"的 SSA 出栈处理，这里
            // 没有实现），就不再假装什么都不用做，生成一段会在运行时
            // 喊出来的 `unimplemented!`，而不是悄悄生成语义错误的代码。
            MirStmt::Assign { dest, value: MirRvalue::Phi { values } } => {
                let dest_base = match dest {
                    MirPlace::Ssa(ssa) => Some(ssa.base_id),
                    _ => None,
                };
                let all_same_base = dest_base.is_some() && values.iter().all(|(_, op)| {
                    match op {
                        MirOperand::Move(MirPlace::Ssa(s)) | MirOperand::Copy(MirPlace::Ssa(s)) => {
                            Some(s.base_id) == dest_base
                        }
                        _ => false,
                    }
                });
                if all_same_base {
                    "    // phi: 各分支已经把值写进了同一个折叠后的变量，这里不需要再生成代码\n".to_string()
                } else {
                    "    unimplemented!(\"Phi node generation: 操作数跟 dest 不共享同一个 base_id，\
需要真正的 SSA 出栈处理（在每个来源块末尾插入赋值），当前 codegen 还没实现这种情况\");\n".to_string()
                }
            }
            MirStmt::Assign { dest, value } => {
                let dest_str = Self::place_to_string(dest, ctx);
                let value_str = Self::rvalue_to_string(value, ctx);
                format!("    {} = {};\n", dest_str, value_str)
            }
            MirStmt::ExprStmt(value) => {
                let value_str = Self::rvalue_to_string(value, ctx);
                format!("    {};\n", value_str)
            }
            MirStmt::Drop { place } => {
                let place_str = Self::place_to_string(place, ctx);
                format!("    drop({});\n", place_str)
            }
            MirStmt::SetMetadata { place, key, value } => {
                let place_str = Self::place_to_string(place, ctx);
                format!("    // set metadata: {}: {} = {}\n", place_str, key, value)
            }
            MirStmt::EffectCheck { effect } => {
                format!("    // effect check: {}\n", effect)
            }
        }
    }

    // ===== 生成终止器：单块函数版本 =====
    // 单块函数不可能有第二个块可跳，Goto/If 出现在这里说明上游 CFG
    // 构造有 bug——直接在生成代码里 panic 出来，方便定位是哪个函数。
    fn gen_terminator_single(term: &MirTerminator, ctx: &CodegenContext) -> String {
        match term {
            MirTerminator::Return(Some(op)) => {
                format!("    return {};\n", Self::operand_to_string(op, ctx))
            }
            MirTerminator::Return(None) => "    return;\n".to_string(),
            MirTerminator::Unreachable => "    unreachable!();\n".to_string(),
            MirTerminator::Goto(_) | MirTerminator::If { .. } | MirTerminator::Switch { .. } => {
                "    unreachable!(\"single-block function has a Goto/If/Switch terminator — mir_builder bug\");\n".to_string()
            }
            // 关键修复（Placeholder/Unreachable 拆分）：mir.rs 新增的
            // Placeholder 专门表示"这个块的终止器还没被真正设置过"（见
            // mir.rs 里 MirTerminator 定义处的说明）。走到 codegen 这一步
            // 还留着 Placeholder，说明 mir_builder.rs 某条构建路径漏了
            // 给某个块设置终止器，是编译器自身的缺陷——跟上面
            // Goto/If/Switch 那支同样的处理方式：生成一段带着诊断信息
            // 的 `unreachable!()`，而不是悄悄当成真正的 Unreachable
            // （那样会把"没写完"和"真的到不了"混为一谈，掩盖构建缺陷）。
            MirTerminator::Placeholder => {
                "    unreachable!(\"block terminator is still Placeholder — mir_builder bug\");\n".to_string()
            }
        }
    }

    // ===== 生成终止器：多块函数版本（loop + match 分发） =====
    fn gen_terminator_dispatch(term: &MirTerminator, ctx: &CodegenContext) -> String {
        match term {
            MirTerminator::Return(Some(op)) => {
                format!("    return {};\n", Self::operand_to_string(op, ctx))
            }
            MirTerminator::Return(None) => "    return;\n".to_string(),
            MirTerminator::Goto(target) => {
                format!("    __block = {}; continue;\n", target)
            }
            MirTerminator::If { cond, then_block, else_block } => {
                let cond_str = Self::operand_to_string(cond, ctx);
                format!(
                    "    if {} {{ __block = {}; }} else {{ __block = {}; }}\n    continue;\n",
                    cond_str, then_block, else_block
                )
            }
            MirTerminator::Unreachable => "    unreachable!();\n".to_string(),
            // 关键新增：对应 mir.rs 新增的 MirTerminator::Switch——按
            // targets 列出的每个 (Literal, 目标块) 生成一个 match 分支，
            // 落不到任何一条的走 default。
            //
            // 关键修复：原来这里对着 `(discr_ty, lit)` 做了一次没有必要
            // 、而且编译不过的特判——`Type::Isize`/`Type::Usize` 这两个
            // 变体在 ast.rs 里根本不存在（Literal 里有 Isize/Usize，但
            // Type 里没有对应的类型变体，这两者本来就不是一一对应的），
            // 引用不存在的枚举变体是硬编译错误；而且 `Literal::Int(v)`
            // 这个变体在这一轮改动里也已经被拆成 Int8..Int128/
            // UInt8..UInt128 一堆按位宽区分的变体了，同样不存在。
            //
            // 实际上这整套特判都是多余的：Rust 的 `match` 模式里写字面
            // 量（数字/字符/布尔），跟把同一个字面量写在表达式位置的
            // 语法是完全一样的（`5 => ...` 和 `let x = 5;` 都合法、都靠
            // 上下文推出具体的数值类型），不需要额外根据 discr_ty 选
            // 不同的渲染方式——`literal_to_string` 已经能把任意 Literal
            // 变体渲染成合法的 Rust 字面量语法，直接复用即可。
            MirTerminator::Switch { discr, discr_ty: _, targets, default } => {
                let discr_str = Self::operand_to_string(discr, ctx);
                let mut code = format!("    match {} {{\n", discr_str);
                for (lit, target) in targets {
                    let lit_str = Self::literal_to_string(lit);
                    code.push_str(&format!("        {} => {{ __block = {}; }}\n", lit_str, target));
                }
                code.push_str(&format!("        _ => {{ __block = {}; }}\n", default));
                code.push_str("    }\n    continue;\n");
                code
            }
            // 关键修复（Placeholder/Unreachable 拆分）：同单块函数版本
            // 那支——Placeholder 走到 codegen 说明 mir_builder.rs 有
            // 构建缺陷，生成带诊断信息的 unreachable!()。
            MirTerminator::Placeholder => {
                "    unreachable!(\"block terminator is still Placeholder — mir_builder bug\");\n".to_string()
            }
        }
    }


    // ===== Place → Rust 字符串 =====
    fn place_to_string(place: &MirPlace, ctx: &CodegenContext) -> String {
        match place {
            // 关键修复：`MirPlace::Local` 这个变体在 mir.rs 更早一轮已经
            // 被彻底删掉了（"SSA 完整版，Local 被废弃"）——mir.rs 的
            // MirPlace 定义现在只有 Ssa/Field/Index/Deref/EnumPayload
            // 五种，原来这里还留着一支 `MirPlace::Local(id) => ...`，
            // 对着一个已经不存在的枚举变体做匹配，编译不过（E0599）。
            // 所有原来经 Local 寻址的东西（cond_temp/disc_temp/
            // dest_base 这些内部临时变量）现在统一经 Ssa 寻址，下面
            // MirPlace::Ssa 那支已经在处理了，不需要另开一支。
            //
            // 关键修复（Sym/Static 搬家）：mir.rs 又把 Static（内建
            // 关联常量）和 Sym（符号形状引用）都从 MirPlace 挪去了
            // MirOperand——它们是值，不是"位置"（见 mir.rs 里 MirPlace
            // 定义处的说明）。原来这里的 `MirPlace::Static(name) =>
            // name.clone()` 分支删掉，等价的逻辑挪到下面
            // operand_to_string 的 MirOperand::Static 分支。
            MirPlace::Field { base, field } => {
                format!("{}.{}", Self::place_to_string(base, ctx), field)
            }
            // 关键修复：跟上面 gen_function 里声明变量那段的说明是同一
            // 件事——不按 (base_id, version) 单独起名，直接复用
            // base_id 对应的、已经在 ctx.locals 里声明好的那个变量名，
            // 把同一个源变量的所有 SSA 版本折叠回同一个 Rust 变量。
            // fallback 的 `__local_{base_id}` 只在 ctx.locals 里查不到
            // （理论上不该发生，locals 表应该覆盖所有 base_id）时兜底，
            // 图的是生成一段能定位问题的代码，而不是直接 panic 掉整个
            // 函数的生成。
            MirPlace::Ssa(ssa) => ctx.locals.get(&ssa.base_id)
                .cloned()
                .unwrap_or_else(|| format!("__local_{}", ssa.base_id)),
            MirPlace::Index { base, index } => {
                format!("{}[{}]", Self::place_to_string(base, ctx), Self::operand_to_string(index, ctx))
            }
            MirPlace::Deref(base) => {
                format!("*({})", Self::place_to_string(base, ctx))
            }
            // 关键新增：对应 mir.rs 新增的 MirPlace::EnumPayload——
            // EnumVariantWithBinding 模式（`Ok(v) => ...`）要把"假设
            // base 是 variant_name 这个变体"时带的那份数据取出来。这
            // 门语言里每个变体最多带一个 payload
            // （EnumVariant.ty: Option<Type>），落地成一次带
            // unreachable! 兜底的 match 就够表达了——兜底分支正常运行
            // 时走不到（Switch 已经在外层用判别式筛过一轮，能进到用
            // EnumPayload 的这个分支块，说明判别式确实等于这个变体），
            // 真走到了说明上游 Switch/Discriminant 构造出了 bug，用
            // panic 而不是生成一段编译不过或者行为不对的代码来暴露它。
            // 这个操作是自给自足的——enum_name/variant_name 都已经
            // 存在 MirPlace::EnumPayload 自己身上，不需要额外去查
            // MirProgram.enums，不属于下面 Discriminant 那种"缺信息"
            // 的情况，能直接实现。
            MirPlace::EnumPayload { base, enum_name, variant_name } => {
                format!(
                    "match {} {{ {}::{}(__payload) => __payload, _ => unreachable!(\"EnumPayload: value did not match expected variant `{}`\") }}",
                    Self::place_to_string(base, ctx), enum_name, variant_name, variant_name
                )
            }
        }
    }

    // ===== 操作数 → Rust 字符串 =====
    fn operand_to_string(op: &MirOperand, ctx: &CodegenContext) -> String {
        match op {
            MirOperand::Copy(place) => Self::place_to_string(place, ctx),
            MirOperand::Move(place) => Self::place_to_string(place, ctx),
            MirOperand::Constant(lit) => Self::literal_to_string(lit),
            // 关键新增（Sym/Static 搬家）：这两个变体从 MirPlace 挪过来
            // 之后，落地成 Rust 代码的逻辑原样照搬过来——Static 的
            // 字符串本来就是一段合法的、可以裸写的 Rust 关联常量路径
            // （如 `i128::MAX`），直接输出；Sym 目前在 sema/mir_builder
            // 里都还没有真正的符号求解语义，落到 codegen 这一层还没有
            // "该生成什么 Rust 代码"的答案，先给一个明确的
            // `unimplemented!` 而不是悄悄把符号名当成变量名裸写出去
            // （生成一个引用不存在标识符的 Rust 表达式，编译不过还不
            // 好定位）。
            MirOperand::Sym(name) => format!(
                "unimplemented!(\"Sym<{}> 尚未实现代码生成：符号形状还没有真正的求解/绑定语义\")",
                name
            ),
            MirOperand::Static(name) => name.clone(),
        }
    }

    // ===== Rvalue → Rust 字符串 =====
    fn rvalue_to_string(rv: &MirRvalue, ctx: &CodegenContext) -> String {
        match rv {
            MirRvalue::Use(op) => Self::operand_to_string(op, ctx),
            MirRvalue::BinaryOp(op, left, right) => {
                let l = Self::operand_to_string(left, ctx);
                let r = Self::operand_to_string(right, ctx);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Eq => "==",
                    BinaryOp::Neq => "!=",
                    BinaryOp::Lt => "<",
                    BinaryOp::Gt => ">",
                    BinaryOp::Le => "<=",
                    BinaryOp::Ge => ">=",
                    BinaryOp::And => "&&",
                    BinaryOp::Or => "||",
                };
                format!("({}) {} ({})", l, op_str, r)
            }
            MirRvalue::UnaryOp(op, operand) => {
                let inner = Self::operand_to_string(operand, ctx);
                match op {
                    UnaryOp::Neg => format!("-({})", inner),
                    UnaryOp::Not => format!("!({})", inner),
                }
            }
            MirRvalue::Cast(operand, ty) => {
                let inner = Self::operand_to_string(operand, ctx);
                let ty_str = Self::type_to_rust(ty);
                format!("({} as {})", inner, ty_str)
            }
            MirRvalue::Call { func, args, is_intrinsic: _, intrinsic_name, generic_args } => {
                // 小重构：原来这三处（已注册的 intrinsic、未注册但仍标了
                // intrinsic_name 的、以及完全不是 intrinsic 的普通调用）
                // 各自重复了一遍"把参数和泛型实参拼成 `name::<T>(a, b)`"
                // 的格式化逻辑，容易改一处忘改另一处。抽成一个小闭包。
                let format_call = |call_name: &str| -> String {
                    let args_str: Vec<String> = args.iter()
                        .map(|a| Self::operand_to_string(a, ctx))
                        .collect();
                    let generic_str = if !generic_args.is_empty() {
                        let types: Vec<String> = generic_args.iter().map(Self::type_to_rust).collect();
                        format!("::<{}>", types.join(", "))
                    } else {
                        String::new()
                    };
                    format!("{}{}({})", call_name, generic_str, args_str.join(", "))
                };

                if let Some(name) = intrinsic_name {
                    match name {
                        IntrinsicFn::Panic => {
                            // 关键修复：`args.first()` 是 `None` 时（源码
                            // 里 `panic()` 不带消息），`unwrap_or_default()`
                            // 给出空字符串，原来的写法会拼出
                            // `panic!("{}", )`——逗号后面是空的，这不是
                            // 合法的宏参数（"unexpected end of macro
                            // invocation"）。没有参数时应该生成不带格式
                            // 串的 `panic!()`，这本身就是合法、且语义
                            // 正确的"不带消息的 panic"。
                            match args.first() {
                                Some(a) => format!("panic!(\"{}\", {})", "{}", Self::operand_to_string(a, ctx)),
                                None => "panic!()".to_string(),
                            }
                        }
                        IntrinsicFn::Print => {
                            // 同上，print() 不带参数时生成 `println!()`
                            // （只输出一个换行），而不是拼出同样非法的
                            // `println!("{}", )`。
                            match args.first() {
                                Some(a) => format!("println!(\"{}\", {})", "{}", Self::operand_to_string(a, ctx)),
                                None => "println!()".to_string(),
                            }
                        }
                        IntrinsicFn::FromUtf8Unchecked => {
                            // 关键修复：`std::str::from_utf8_unchecked`
                            // 是一个 unsafe fn，在 unsafe 块之外调用是
                            // 硬编译错误（"call to unsafe function
                            // requires unsafe function or block"）。原来
                            // 这里直接裸调用，生成出来的代码过不了编译。
                            //
                            // 这里只包住这一次调用本身（`unsafe { expr
                            // }` 作用在表达式上，不需要一整个语句块），
                            // 这是一个自给自足、稳妥的局部修复——但要
                            // 提醒一下背后更大的一个缺口：MIR 层面
                            // 表示"这段代码在源码里写在 unsafe 块里"用
                            // 的是 `MirStmt::EffectCheck { effect:
                            // "unsafe" }` 这一条打了个标记的语句，
                            // mir_builder.rs 把 unsafe 块本身的花括号
                            // 边界拍平掉了，只在入口留了这一条标记，MIR
                            // 里已经找不到"unsafe 范围到哪里结束"这个
                            // 信息了。而 gen_stmt 对 EffectCheck 的处理
                            // 只是生成一行注释，不是真的 `unsafe {`。
                            // 也就是说，如果以后有其它 intrinsic 也需要
                            // 真正的 unsafe 才能调用（裸指针解引用、FFI
                            // 之类），没法靠 EffectCheck 在这里恢复出一
                            // 个正确的 unsafe 作用域——只能像这里一样为
                            // 每个需要 unsafe 的具体操作单独在表达式级
                            // 别上手动包一层。要连 `verify`/`unsafe`
                            // 块本身的边界都完整保留，需要 mir_builder.rs
                            // 那边把"unsafe 块结束"也显式标出来，这不是
                            // codegen.rs 这一个文件能补全的。
                            let arg = args.first().map(|a| Self::operand_to_string(a, ctx)).unwrap_or_default();
                            format!("unsafe {{ std::str::from_utf8_unchecked({}) }}", arg)
                        }
                        // 关键修复：原来这里有一支 `IntrinsicName::I128Max
                        // => { get_constant(*name)... }` 分支，是自举团队
                        // 混淆了 intrinsic.rs 里两个独立的枚举——I128Max
                        // 是 IntrinsicConst 的变体，根本不属于这里的
                        // IntrinsicFn；`intrinsic_name` 这个字段的类型是
                        // Option<IntrinsicFn>，永远不可能是 I128Max，这支
                        // 分支在类型层面就是不可达的死代码（改名成
                        // IntrinsicFn 之后甚至连编译都过不了：IntrinsicFn
                        // 压根没有 I128Max 这个变体）。i128::MAX 这类关联
                        // 常量真正的落地路径是 mir_builder.rs 里提前识别
                        // 出来、直接产出 MirOperand::Static（这个值现在
                        // 挂在 MirOperand 上，不是 MirPlace——见 mir.rs
                        // 里 MirPlace 定义处关于 Sym/Static 搬家的说明），
                        // 根本不会走到 MirRvalue::Call 这里（见 mir_builder.rs 里那段
                        // "内建关联常量" 的注释），所以这里不需要、也不能
                        // 保留一个处理常量的分支，直接删掉，让常量相关的
                        // 调用全部落进下面的通用 intrinsic 分支处理。
                        _ => {
                            // `name` 在这里是 `&IntrinsicFn`（从上面
                            // `if let Some(name) = intrinsic_name` 一路
                            // match ergonomics 下来的），但 get_intrinsic
                            // 要的是按值传的 IntrinsicFn，直接传引用类型
                            // 对不上（E0308）。IntrinsicFn 是 Copy，解一次
                            // 引用就行，不需要 clone。
                            if let Some(intrinsic) = get_intrinsic(*name) {
                                format_call(intrinsic.link_name)
                            } else {
                                format_call(func)
                            }
                        }
                    }
                } else {
                    format_call(func)
                }
            }
            MirRvalue::MethodCall { receiver, method, args, generic_args } => {
                let recv_str = Self::operand_to_string(receiver, ctx);
                let args_str: Vec<String> = args.iter()
                    .map(|a| Self::operand_to_string(a, ctx))
                    .collect();
                let generic_str = if !generic_args.is_empty() {
                    let types: Vec<String> = generic_args.iter().map(Self::type_to_rust).collect();
                    format!("::<{}>", types.join(", "))
                } else {
                    String::new()
                };
                if args_str.is_empty() {
                    format!("({}).{}{}()", recv_str, method, generic_str)
                } else {
                    format!("({}).{}{}({})", recv_str, method, generic_str, args_str.join(", "))
                }
            }
            MirRvalue::StructInit { struct_name, generic_args, fields } => {
                let args_str = if generic_args.is_empty() {
                    String::new()
                } else {
                    let types = generic_args.iter().map(Self::type_to_rust).collect::<Vec<_>>().join(", ");
                    format!("::<{}>", types)
                };
                let fields_str: Vec<String> = fields.iter()
                    .map(|(name, op)| format!("{}: {}", name, Self::operand_to_string(op, ctx)))
                    .collect();
                format!("{}{} {{ {} }}", struct_name, args_str, fields_str.join(", "))
            }
            MirRvalue::EnumVariantConstruction { enum_name, generic_args, variant_name, args } => {
                let args_str = if generic_args.is_empty() {
                    String::new()
                } else {
                    let types = generic_args.iter().map(Self::type_to_rust).collect::<Vec<_>>().join(", ");
                    format!("::<{}>", types)
                };
                let arg_vals: Vec<String> = args.iter()
                    .map(|a| Self::operand_to_string(a, ctx))
                    .collect();
                if arg_vals.is_empty() {
                    format!("{}{}::{}", enum_name, args_str, variant_name)
                } else {
                    format!("{}{}::{}({})", enum_name, args_str, variant_name, arg_vals.join(", "))
                }
            }
            MirRvalue::Ref { mutable, place } => {
                let place_str = Self::place_to_string(place, ctx);
                if *mutable {
                    format!("&mut {}", place_str)
                } else {
                    format!("&{}", place_str)
                }
            }
            MirRvalue::ArrayLiteral(elements) => {
                let elems_str: Vec<String> = elements.iter()
                    .map(|e| Self::operand_to_string(e, ctx))
                    .collect();
                format!("[{}]", elems_str.join(", "))
            }
            MirRvalue::Phi { values } => {
                "unimplemented!(\"Phi node generation\")".to_string()
            }
            // 关键修复（过期注释，容易误导）：这里原来的注释说"先用一段
            // 说明清楚缺什么的 panic 占位"，但下面这份实现其实早就是
            // 真正能跑的代码了（用 ctx.get_variants/
            // enum_variant_has_payload 生成一段按声明顺序列出每个变体、
            // 挨个赋下标的 match 表达式），不是占位——旧注释描述的
            // "需要把 &[MirEnum] 一路穿过好几层函数签名"这件事已经通过
            // gen_function 提前把 enum_variants/enum_variant_has_payload
            // 转换好、装进 CodegenContext 里解决了，不需要再改函数签名。
            // 留着这段"还没做"的说明会让下一个读到这里的人误以为
            // Discriminant 还是个 panic 占位，所以删掉，只留实现本身。
            MirRvalue::Discriminant { value, enum_name } => {
                let variants = ctx.get_variants(enum_name)
                    .unwrap_or_else(|| panic!("enum `{}` not found", enum_name));
                let has_payloads = ctx.enum_variant_has_payload.get(enum_name)
                    .unwrap_or_else(|| panic!("payload info for enum `{}` not found", enum_name));
                let scrutinee = Self::operand_to_string(value, ctx);
                let mut code = format!("match {} {{\n", scrutinee);
                for (idx, (variant, &has_payload)) in variants.iter().zip(has_payloads.iter()).enumerate() {
                    let pattern = if has_payload {
                        format!("{}::{}(..)", enum_name, variant)
                    } else {
                        format!("{}::{}", enum_name, variant)
                    };
                    code.push_str(&format!("        {} => {},\n", pattern, idx));
                }
                code.push_str("    }");
                code
            }
        }
    }

    // ===== 字面量 → Rust 字符串 =====
    // 关键修复：这一轮 ast.rs 把 `Literal::Int`/`Literal::Float` 拆掉
    // 了——Int 拆成 Int8..Int128/UInt8..UInt128/Isize/Usize 按位宽和
    // 符号区分的一堆变体，Float 拆成 Float16/Float32/Float64。原来这里
    // 还是对着已经不存在的 `Literal::Int(v)`/`Literal::Float(v)` 匹配，
    // 编译不过；而且原来的 match 压根没有 `Literal::Char` 这一支，
    // 少一个变体的 match 本身就不是穷尽匹配，同样编译不过（E0004）。
    fn literal_to_string(lit: &Literal) -> String {
        match lit {
            // 整数这十个变体除了具体的 Rust 类型后缀不一样，其它都
            // 相同，不分开重复写。
            Literal::Int8(v) => format!("{}i8", v),
            Literal::Int16(v) => format!("{}i16", v),
            Literal::Int32(v) => format!("{}i32", v),
            Literal::Int64(v) => format!("{}i64", v),
            Literal::Int128(v) => format!("{}i128", v),
            Literal::UInt8(v) => format!("{}u8", v),
            Literal::UInt16(v) => format!("{}u16", v),
            Literal::UInt32(v) => format!("{}u32", v),
            Literal::UInt64(v) => format!("{}u64", v),
            Literal::UInt128(v) => format!("{}u128", v),
            Literal::Isize(v) => format!("{}isize", v),
            Literal::Usize(v) => format!("{}usize", v),
            // 关键提醒：Float16 存储成 f32（ast.rs 那边的原话："Rust
            // 没有原生 f16，但我们可以用 f32 模拟"），这里跟着用同一套
            // f32 渲染逻辑——但这只是渲染层面的模拟：如果构造这个字面
            // 量的上游（sema/hir_builder，不在这几个文件里）没有先把
            // 值舍入到 f16 能精确表示的精度就直接把 f64/f32 源值塞进
            // 来，这里生成出来的 f32 常量会比真正的 f16 多出一截 f32
            // 独有的精度，跟"这是一个 f16 值"这个声明不符。这个检查
            // 目前没有地方做，这里只能提醒一下，不是这个函数自己能
            // 解决的问题——你提到"f16 要加东西专门检查"，如果指的就是
            // 这一点，检查需要加在构造 Literal::Float16 的地方（把值
            // 舍入/验证到 f16 精度），不是这个纯渲染函数。
            Literal::Float16(v) => Self::format_float_literal(*v as f64, "f32"),
            Literal::Float32(v) => Self::format_float_literal(*v as f64, "f32"),
            Literal::Float64(v) => Self::format_float_literal(*v, "f64"),
            Literal::Bool(v) => v.to_string(),
            // 关键新增：原来的 match 完全没有这一支，不是穷尽匹配，
            // 编译不过。`{:?}`（Debug）对 char 的实现产出的正好是一段
            // 合法的、转义好的 Rust char 字面量语法（比如 `'a'`、
            // 遇到 `'`/`\` 之类也会正确转义），直接复用，不用自己拼
            // 引号。
            Literal::Char(c) => format!("{:?}", c),
            // 关键修复：原来是 `format!("\"{}\"", s)`，把字符串内容原样
            // 塞进一对引号里，完全没做转义。只要源字符串本身包含
            // `"`、`\`、换行之类的字符，生成出来的 Rust 源码要么语法
            // 错误（提前把字符串字面量截断），要么虽然能编译但内容跟
            // 原始字符串不一致（反斜杠被 Rust 词法分析当成转义序列的
            // 开头，解析出跟源字符串不同的内容）。`{:?}`（Debug）对
            // str/String 的实现正好就是"生成一段合法的、转义好的 Rust
            // 字符串字面量语法"，是这里该用的格式化方式，不是巧合。
            // 关键修复：配合上面 `type_to_rust` 把 `Type::Str` 改成
            // `String`（原因见那边的说明）——`format!("{:?}", s)` 产出
            // 的是一段 `&'static str` 字面量语法（比如 `"hello"`），如果
            // 声明类型是 `String`，`let x: String = "hello";` 会类型
            // 不匹配（`&str` 不会自动转成 `String`）。补上 `.to_string()`
            // 把它变成一个 `String` 值，两边类型才能对上。
            Literal::String(s) => format!("{:?}.to_string()", s),
            Literal::Unit => "()".to_string(),
            Literal::ByteString(bytes) => {
                // 补充健壮性：每个字节都带上 `u8` 后缀。原来写
                // `&[1, 2, 3][..]`，类型要靠外层上下文（比如
                // `let x: &[u8] = ...;` 里的类型标注）反向推断成 u8，大
                // 多数场景下能推对，但只要这个字面量出现在推不出具体
                // 元素类型的位置（比如直接传给一个还没实例化的泛型
                // 参数），Rust 就会按默认整数类型 i32 推导，跟 bytes"..."
                // 该有的 &[u8] 类型对不上。每个元素自己带类型后缀，就不
                // 用依赖外部上下文了。
                let items: Vec<String> = bytes.iter().map(|b| format!("{}u8", b)).collect();
                format!("&[{}][..]", items.join(", "))
            }
        }
    }

    // 关键新增：Literal::Int(v)/Literal::Float(v) 原来各自写了一遍
    // NaN/±inf/整数值浮点数的处理逻辑，Float16/Float32/Float64 拆开
    // 之后如果每个变体都各抄一遍，是那种"以后只改了一处、另外两处
    // 悄悄失配"的隐患——抽成一个共用函数，浮点数格式化规则只有这
    // 一处需要维护。
    fn format_float_literal(v: f64, suffix: &str) -> String {
        if v.is_nan() {
            format!("{}::NAN", suffix)
        } else if v.is_infinite() {
            if v > 0.0 {
                format!("{}::INFINITY", suffix)
            } else {
                format!("{}::NEG_INFINITY", suffix)
            }
        } else if v.fract() == 0.0 {
            format!("{:.1}{}", v, suffix)
        } else {
            format!("{}{}", v, suffix)
        }
    }

    // ===== 类型 → Rust 字符串 =====
    // 关键修复：原来这个 match 的分支类型对不上——大部分分支是
    // `&'static str` 字面量（"i8"/"bool"/...），TypeParam/Struct/Enum
    // 三支返回的 `name` 是 `&String`，Generic/ConstIntArray/Ref/Slice
    // 几支用 `format!(...)` 返回的是**拥有所有权的 `String`**，match
    // 结束后又对整个 match 表达式调用 `.to_string()`。`&str` 和
    // `&String` 之间有 deref 强制转换，两者能凑到一起；但 `String` 不会
    // 反向强制转换成 `&str`（也不会有任何自动转换把 `&str` 变成
    // `String`）——同一个 match 里混了这三种类型，编译器没法把所有分支
    // 统一成同一个类型，这个函数本身就编译不过，导致 codegen.rs 这个
    // crate 根本没法构建，绝不是"能编译但结果不对"的级别。
    // 改法：让每个分支都直接产出 `String`（字面量分支补 `.to_string()`，
    // `name` 分支改 `.clone()`），去掉结尾多余的 `.to_string()`。
    fn type_to_rust(ty: &Type) -> String {
        match ty {
            Type::I8 => "i8".to_string(),
            Type::I16 => "i16".to_string(),
            Type::I32 => "i32".to_string(),
            Type::I64 => "i64".to_string(),
            Type::I128 => "i128".to_string(),
            Type::U8 => "u8".to_string(),
            Type::U16 => "u16".to_string(),
            Type::U32 => "u32".to_string(),
            Type::U64 => "u64".to_string(),
            Type::U128 => "u128".to_string(),
            // 关键修复：原来映射成 Rust 的 `f16` 类型——`f16` 目前在
            // Rust 里还是不稳定特性（需要 `#![feature(f16)]`），普通
            // stable 工具链直接编译不过；而且这跟 `Literal::Float16`
            // 的存储方式也对不上——那边已经明确选择了"用 f32 模拟
            // f16"（ast.rs 里的原话），类型这边却还映射到一个稳定版
            // 编译不过的真 `f16`，同一个"f16"概念在类型和字面量两处
            // 用了两套不一致的落地方式：一个变量声明成 `f16` 类型，
            // 却拿一个 `f32` 字面量去初始化，类型对不上。改成跟字面量
            // 那边保持一致，也用 `f32`——这样至少类型和值是自洽的，
            // 只是"用 f32 模拟 f16"这件事本身意味着数值精度上限是
            // f32 而不是真正的 f16（多出的精度不会在这里被截断，需要
            // 在构造 Literal::Float16 的地方，也就是 sema/hir_builder
            // 那一侧，把值先舍入到 f16 能精确表示的范围）——这就是你
            // 说的"要加东西专门检查"，检查点不在这个类型渲染函数里。
            Type::F16 => "f32".to_string(),
            Type::F32 => "f32".to_string(),
            Type::F64 => "f64".to_string(),
            Type::Bool => "bool".to_string(),
            Type::Char => "char".to_string(),
            // 关键修复（有一定推测成分，说明写在下面）：原来这里映射成
            // `&str`——在函数参数/局部变量的类型位置上，裸 `&str`
            // （省略生命周期）是合法的；但 `gen_struct`/`gen_enum` 也会
            // 拿 `Type::Str` 类型的字段调用这个函数，Rust 的结构体/枚举
            // 字段类型里是不允许省略生命周期的（`struct Foo { s: &str }`
            // 编译不过，报 "missing lifetime specifier"，需要显式的
            // 生命周期参数）——这门语言目前生成的结构体/枚举定义里没有
            // 任何生命周期参数，任何带 Str 字段的结构体都会炸。
            // 改成映射到拥有所有权的 `String`：函数参数/局部变量位置
            // 用 `String` 一样合法（只是不如 `&str` 零成本），结构体
            // 字段位置则从"编译不过"变成"能编译"。如果这门语言的
            // `Type::Str` 本来就是想始终表示"借用"（类似 `Type::Slice`
            // 那样，设计上要求外面永远套一层 `Type::Ref`），那这里应该
            // 保留 `&str` 不动，改成在 `Type::Ref { inner: Str, .. }`
            // 那一支特殊处理——但 `Type::Str` 本身没有类似 Slice 那样
            // "单独出现没有意义"的说明注释，从其余类型的设计模式（裸
            // 类型 = 拥有所有权，套一层 Ref 才是借用）看，我倾向于认为
            // 这是最初实现时的疏漏，不是有意为之；如果判断错了，这里
            // 请直接改回 `&str`。为了配合这个改动，下面
            // `literal_to_string` 里 `Literal::String` 那支也要跟着从
            // `&'static str` 字面量语法改成拥有所有权的 `String`，两边
            // 类型才能对上。
            Type::Str => "String".to_string(),
            Type::Unit => "()".to_string(),
            Type::Never => "!".to_string(),
            Type::TypeParam(name) => name.clone(),
            Type::Struct(name) => name.clone(),
            Type::Enum(name) => name.clone(),
            Type::SelfType => "Self".to_string(),
            Type::Generic(name, args) => {
                let args_str: Vec<String> = args.iter().map(Self::type_to_rust).collect();
                format!("{}<{}>", name, args_str.join(", "))
            }
            Type::Tensor { .. } => "tch::Tensor".to_string(),
            Type::Privacy(inner, _) => Self::type_to_rust(inner),
            Type::SymInt => "usize".to_string(),
            // 提醒：这一支生成的是 `[v1, v2, ...]`，这是数组*值*的写法，
            // 不是数组*类型*的写法（Rust 的数组类型长这样：`[T; N]`）。
            // `type_to_rust` 这个函数名和其它所有分支的约定都是"产出一段
            // 合法的 Rust 类型语法"，唯独这一支产出的是值语法，用在类型
            // 位置上（比如某个字段/参数声明为 `Type::ConstIntArray`）会
            // 直接编译不过。ConstIntArray 具体打算表达什么语义（const
            // 泛型参数？形状常量？）这几个文件里没有更多线索，不确定
            // 正确的类型渲染该是什么样，不敢瞎猜着"修"，原样保留、只在
            // 这里留个疑点，等你确认它的用途后再改成对的类型语法。
            Type::ConstIntArray(vals) => {
                format!("[{}]", vals.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(", "))
            }
            Type::Ref { mutable, inner } => {
                let inner_str = Self::type_to_rust(inner);
                if *mutable {
                    format!("&mut {}", inner_str)
                } else {
                    format!("&{}", inner_str)
                }
            }
            Type::Slice(inner) => format!("[{}]", Self::type_to_rust(inner)),
            Type::Tuple(elems) => {
                let inner = elems.iter().map(Self::type_to_rust).collect::<Vec<_>>().join(", ");
                format!("({})", inner)
            }
            Type::Array(elem_ty, len) => {
                format!("[{}; {}]", Self::type_to_rust(elem_ty), len)
            }
        }
    }
}
